server:
  port: 8801
# Spring Config
spring:
  application:
    name: client-service
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://mysql:3306/clients_db?createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: false
        format: yaml
        default-context: application
        profile-separator: "-"
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logging Config
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
