server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    discovery:
      eureka:
        enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowed-origins: "http://localhost:5174"
            allowed-methods: "GET, POST, PUT, DELETE"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
